server:
  port: 8082

spring:
  datasource:
    hikari:
      max-lifetime: 300000
      maximum-pool-size: 20

  application:
    name: eventmanager

  profiles:
    active: docker

  liquibase:
    enabled: true
    change-log: db.changelog/master.xml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

logging:
  level:
    root: info
    com.lostway.eventnotificator.aop: info
springdoc:
  swagger-ui:
    url: /event-notificator-openapi.yaml

secret.key: verylongsecretkeyforpetprojecteventmanagerlostway2025

#In second
expiration.time: 3600

scheduler:
  enabled: true
  cron: 0 */10 * * * *
  days-to-delete: 7

