spring:
  kafka:
    bootstrap-servers: localhost:29092, localhost:29093, localhost:29094
  datasource:
    url: jdbc:postgresql://localhost:5434/eventnotificator
    username: postgres
    password: password